export const siteInfo = {
  title: "Andrea Petreti | Blog",
  author: "Andrea Petreti",
  author_image: "/img/author2.jpg",
  position: "Software Engineer",
  location: "Italy",
  headerTitle: "Andrea Petreti",
  slogan: "Love coding",
  description: "A tech enthusiast & self taught learner. Love to talk the way of tech.",
  language: "en-us",
  theme: "light",
  siteUrl: "https://petretiandrea.github.io",
  siteRepo: "#",
  email: "petretiandrea@gmail.com",
  github: "https://github.com/petretiandrea",
  githubUser: "petretiandrea",
  stackoverflow: "#",
  youtube: "#",
  linkedin: "#",
} as const;
